### ISSUE TITLE
How to Get Tab Bar Index?

### ISSUE THREAD

**Issue by KushThakkar** [mho000/MHImageTabBar#2]
Hello, Please tell me how can i get TabBar Index.
 and also How to hide Tab Bar Any of one Tab Click and Also How to unhide that?

**Comment by abuobaida** [comment]
Hello,

You can use the `selectedViewControllerIndex` property to get the index of the selected tab.

For the second point, you want to hide the tab bar after tapping a bar item?

**Comment by mho000** [comment]
Hello,

You can use the selectedViewControllerIndex property to get the index of the selected tab.

For the second point, you want to hide the tab bar after tapping a bar item?
